# Generated by Django 5.1.3 on 2024-12-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verification_status',
            field=models.CharField(choices=[('driver_license', 'Driver License'), ('national_id', 'National ID'), ('passport', 'Passport')], max_length=40),
        ),
    ]
