# Generated by Django 5.1.3 on 2024-12-12 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_email', models.EmailField(max_length=254)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('mortgage', 'Mortgage')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term_months', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
